# Contact details and external links shown in the homepage header.
contact:
  email: wenke.du@inria.fr
  thesis: https://theses.ifpen.fr/these/conception-dun-framework-dinference-de-dnns-dedie-la-simulation-massivement-parallele-pour
